### ISSUE TITLE
What difference with original c0bra/svelma project?

### ISSUE THREAD

**Issue by alexander-mart** [saravanabalagi/svelma#7]

**Comment by saravanabalagi** [comment]
Hi, this repo is supposed to be a fork that I use for dev purposes and to raise pull requests ⬆️ to merge with c0bra/svelma. Unfortunately, there are some obvious bugs and pull requests can take sometime to be accepted. One example would be [tabs](https://saravanabalagi.github.io/svelma/components/tabs) vs [c0bra/svelma/tabs](https://c0bra.github.io/svelma/components/tabs). 

It's open-source, people contribute and review code at their own convenience (just like how I missed and didn't reply to this issue for months, sorry 😢), it's understandable. I use svelma in production for many of my own apps. So I chose to directly depend on this fork instead, where I can instantly fix issues and publish to npm.

I usually add extra stuff I add on README, but so far, I didn't add any component. Just bug fixes. I hope to keep this updated with upstream, and might add more stuff as I make more apps and use more components. So feel free to use this fork, raise issues, pull requests and when I become lazy 🤷‍♂️ , don't hesitate to have your own fork that you can depend on!
